app:
  date:
    format: yyyy-MM-dd
spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    username: jonas
    password: abc1234
    url: "jdbc:postgresql://localhost:5432/techchallange?createDatabaseIfNotExist=false"
  web:
    locale: pt_BR
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update